# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.10
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 152750039+code-alexander@users.noreply.github.com
author_name: code-alexander
code_tours: false
contract_name: storage
deployment_language: python
ide_jetbrains: false
ide_vscode: false
preset_name: custom
project_name: blockchain
python_linter: none
use_dispenser: false
use_github_actions: false
use_pre_commit: false
use_python_black: false
use_python_mypy: false
use_python_pip_audit: false
use_python_pytest: true

